project:
  type: book
  base-url: /classical-math-foundations/

book:
  title: "Classical Mathematics Foundations: Euclid's Elements"
  author: "Christian Bolander"
  date: "3/16/2026"
  chapters:
    - index.qmd

    - part: "Introduction"
      chapters:
      - intro.qmd
      - introduction/using.qmd

    - part: "Book I"
      chapters:
      - book1/propositionI.qmd
    
    - part: "References"
      chapters:
      - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: book
  epub: default

